// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.io.Serializable;
import org.inbloom.content.domain.AgeRange;

privileged aspect AgeRange_Roo_Serializable {
    
    declare parents: AgeRange implements Serializable;
    
    private static final long AgeRange.serialVersionUID = 1L;
    
}
