// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import org.inbloom.content.domain.Alignment;

privileged aspect Alignment_Roo_Jpa_Entity {
    
    declare @type: Alignment: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Alignment.id;
    
    @Version
    @Column(name = "version")
    private Integer Alignment.version;
    
    public Long Alignment.getId() {
        return this.id;
    }
    
    public void Alignment.setId(Long id) {
        this.id = id;
    }
    
    public Integer Alignment.getVersion() {
        return this.version;
    }
    
    public void Alignment.setVersion(Integer version) {
        this.version = version;
    }
    
}
