// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.inbloom.content.domain.Alignment;

privileged aspect Alignment_Roo_Json {
    
    public String Alignment.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public String Alignment.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(this);
    }
    
    public static Alignment Alignment.fromJsonToAlignment(String json) {
        return new JSONDeserializer<Alignment>().use(null, Alignment.class).deserialize(json);
    }
    
    public static String Alignment.toJsonArray(Collection<Alignment> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static String Alignment.toJsonArray(Collection<Alignment> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<Alignment> Alignment.fromJsonArrayToAlignments(String json) {
        return new JSONDeserializer<List<Alignment>>().use(null, ArrayList.class).use("values", Alignment.class).deserialize(json);
    }
    
}
