// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.PostPersist;
import javax.persistence.PostUpdate;
import javax.persistence.PreRemove;
import org.apache.solr.client.solrj.SolrQuery;
import org.apache.solr.client.solrj.SolrServer;
import org.apache.solr.client.solrj.response.QueryResponse;
import org.apache.solr.common.SolrInputDocument;
import org.inbloom.content.domain.Alignment;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Async;

privileged aspect Alignment_Roo_SolrSearch {
    
    @Autowired
    transient SolrServer Alignment.solrServer;
    
    public static QueryResponse Alignment.search(String queryString) {
        String searchString = "Alignment_solrsummary_t:" + queryString;
        return search(new SolrQuery(searchString.toLowerCase()));
    }
    
    public static QueryResponse Alignment.search(SolrQuery query) {
        try {
            return solrServer().query(query);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return new QueryResponse();
    }
    
    public static void Alignment.indexAlignment(Alignment alignment) {
        List<Alignment> alignments = new ArrayList<Alignment>();
        alignments.add(alignment);
        indexAlignments(alignments);
    }
    
    @Async
    public static void Alignment.indexAlignments(Collection<Alignment> alignments) {
        List<SolrInputDocument> documents = new ArrayList<SolrInputDocument>();
        for (Alignment alignment : alignments) {
            SolrInputDocument sid = new SolrInputDocument();
            sid.addField("id", "alignment_" + alignment.getId());
            sid.addField("alignment.standard_t", alignment.getStandard());
            sid.addField("alignment.resource_t", alignment.getResource());
            sid.addField("alignment.alignmenttype_t", alignment.getAlignmentType());
            sid.addField("alignment.id_l", alignment.getId());
            // Add summary field to allow searching documents for objects of this type
            sid.addField("alignment_solrsummary_t", new StringBuilder().append(alignment.getStandard()).append(" ").append(alignment.getResource()).append(" ").append(alignment.getAlignmentType()).append(" ").append(alignment.getId()));
            documents.add(sid);
        }
        try {
            SolrServer solrServer = solrServer();
            solrServer.add(documents);
            solrServer.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    @Async
    public static void Alignment.deleteIndex(Alignment alignment) {
        SolrServer solrServer = solrServer();
        try {
            solrServer.deleteById("alignment_" + alignment.getId());
            solrServer.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    @PostUpdate
    @PostPersist
    private void Alignment.postPersistOrUpdate() {
        indexAlignment(this);
    }
    
    @PreRemove
    private void Alignment.preRemove() {
        deleteIndex(this);
    }
    
    public static SolrServer Alignment.solrServer() {
        SolrServer _solrServer = new Alignment().solrServer;
        if (_solrServer == null) throw new IllegalStateException("Solr server has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return _solrServer;
    }
    
}
