// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.io.Serializable;
import org.inbloom.content.domain.Audience;

privileged aspect Audience_Roo_Serializable {
    
    declare parents: Audience implements Serializable;
    
    private static final long Audience.serialVersionUID = 1L;
    
}
