// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.io.Serializable;
import org.inbloom.content.domain.Lang;

privileged aspect Lang_Roo_Serializable {
    
    declare parents: Lang implements Serializable;
    
    private static final long Lang.serialVersionUID = 1L;
    
}
