// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import org.inbloom.content.domain.LearningMap;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LearningMap_Roo_Configurable {
    
    declare @type: LearningMap: @Configurable;
    
}
