// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.io.Serializable;
import org.inbloom.content.domain.Resource;

privileged aspect Resource_Roo_Serializable {
    
    declare parents: Resource implements Serializable;
    
    private static final long Resource.serialVersionUID = 1L;
    
}
