// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Alignment;
import org.inbloom.content.domain.AlignmentDataOnDemand;
import org.inbloom.content.domain.AlignmentTypeDataOnDemand;
import org.inbloom.content.domain.ResourceDataOnDemand;
import org.inbloom.content.domain.StandardDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AlignmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AlignmentDataOnDemand: @Component;
    
    private Random AlignmentDataOnDemand.rnd = new SecureRandom();
    
    private List<Alignment> AlignmentDataOnDemand.data;
    
    @Autowired
    AlignmentTypeDataOnDemand AlignmentDataOnDemand.alignmentTypeDataOnDemand;
    
    @Autowired
    ResourceDataOnDemand AlignmentDataOnDemand.resourceDataOnDemand;
    
    @Autowired
    StandardDataOnDemand AlignmentDataOnDemand.standardDataOnDemand;
    
    public Alignment AlignmentDataOnDemand.getNewTransientAlignment(int index) {
        Alignment obj = new Alignment();
        return obj;
    }
    
    public Alignment AlignmentDataOnDemand.getSpecificAlignment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Alignment obj = data.get(index);
        Long id = obj.getId();
        return Alignment.findAlignment(id);
    }
    
    public Alignment AlignmentDataOnDemand.getRandomAlignment() {
        init();
        Alignment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Alignment.findAlignment(id);
    }
    
    public boolean AlignmentDataOnDemand.modifyAlignment(Alignment obj) {
        return false;
    }
    
    public void AlignmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Alignment.findAlignmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Alignment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Alignment>();
        for (int i = 0; i < 10; i++) {
            Alignment obj = getNewTransientAlignment(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
