// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Audience;
import org.inbloom.content.domain.AudienceDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect AudienceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AudienceDataOnDemand: @Component;
    
    private Random AudienceDataOnDemand.rnd = new SecureRandom();
    
    private List<Audience> AudienceDataOnDemand.data;
    
    public Audience AudienceDataOnDemand.getNewTransientAudience(int index) {
        Audience obj = new Audience();
        setName(obj, index);
        return obj;
    }
    
    public void AudienceDataOnDemand.setName(Audience obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Audience AudienceDataOnDemand.getSpecificAudience(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Audience obj = data.get(index);
        Long id = obj.getId();
        return Audience.findAudience(id);
    }
    
    public Audience AudienceDataOnDemand.getRandomAudience() {
        init();
        Audience obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Audience.findAudience(id);
    }
    
    public boolean AudienceDataOnDemand.modifyAudience(Audience obj) {
        return false;
    }
    
    public void AudienceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Audience.findAudienceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Audience' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Audience>();
        for (int i = 0; i < 10; i++) {
            Audience obj = getNewTransientAudience(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
