// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Lang;
import org.inbloom.content.domain.LangDataOnDemand;
import org.inbloom.content.domain.LangIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LangIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LangIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LangIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LangIntegrationTest: @Transactional;
    
    @Autowired
    LangDataOnDemand LangIntegrationTest.dod;
    
    @Test
    public void LangIntegrationTest.testCountLangs() {
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", dod.getRandomLang());
        long count = Lang.countLangs();
        Assert.assertTrue("Counter for 'Lang' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LangIntegrationTest.testFindLang() {
        Lang obj = dod.getRandomLang();
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Lang' failed to provide an identifier", id);
        obj = Lang.findLang(id);
        Assert.assertNotNull("Find method for 'Lang' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Lang' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LangIntegrationTest.testFindAllLangs() {
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", dod.getRandomLang());
        long count = Lang.countLangs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Lang', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Lang> result = Lang.findAllLangs();
        Assert.assertNotNull("Find all method for 'Lang' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Lang' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LangIntegrationTest.testFindLangEntries() {
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", dod.getRandomLang());
        long count = Lang.countLangs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Lang> result = Lang.findLangEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Lang' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Lang' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LangIntegrationTest.testFlush() {
        Lang obj = dod.getRandomLang();
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Lang' failed to provide an identifier", id);
        obj = Lang.findLang(id);
        Assert.assertNotNull("Find method for 'Lang' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLang(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Lang' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LangIntegrationTest.testMergeUpdate() {
        Lang obj = dod.getRandomLang();
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Lang' failed to provide an identifier", id);
        obj = Lang.findLang(id);
        boolean modified =  dod.modifyLang(obj);
        Integer currentVersion = obj.getVersion();
        Lang merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Lang' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LangIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", dod.getRandomLang());
        Lang obj = dod.getNewTransientLang(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Lang' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Lang' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Lang' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LangIntegrationTest.testRemove() {
        Lang obj = dod.getRandomLang();
        Assert.assertNotNull("Data on demand for 'Lang' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Lang' failed to provide an identifier", id);
        obj = Lang.findLang(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Lang' with identifier '" + id + "'", Lang.findLang(id));
    }
    
}
