// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.LearningMap;
import org.inbloom.content.domain.LearningMapDataOnDemand;
import org.inbloom.content.domain.StandardDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LearningMapDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LearningMapDataOnDemand: @Component;
    
    private Random LearningMapDataOnDemand.rnd = new SecureRandom();
    
    private List<LearningMap> LearningMapDataOnDemand.data;
    
    @Autowired
    StandardDataOnDemand LearningMapDataOnDemand.standardDataOnDemand;
    
    public LearningMap LearningMapDataOnDemand.getNewTransientLearningMap(int index) {
        LearningMap obj = new LearningMap();
        setName(obj, index);
        setPayload(obj, index);
        return obj;
    }
    
    public void LearningMapDataOnDemand.setName(LearningMap obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void LearningMapDataOnDemand.setPayload(LearningMap obj, int index) {
        String payload = "payload_" + index;
        obj.setPayload(payload);
    }
    
    public LearningMap LearningMapDataOnDemand.getSpecificLearningMap(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LearningMap obj = data.get(index);
        Long id = obj.getId();
        return LearningMap.findLearningMap(id);
    }
    
    public LearningMap LearningMapDataOnDemand.getRandomLearningMap() {
        init();
        LearningMap obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return LearningMap.findLearningMap(id);
    }
    
    public boolean LearningMapDataOnDemand.modifyLearningMap(LearningMap obj) {
        return false;
    }
    
    public void LearningMapDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LearningMap.findLearningMapEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LearningMap' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LearningMap>();
        for (int i = 0; i < 10; i++) {
            LearningMap obj = getNewTransientLearningMap(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
