// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.PartyType;
import org.inbloom.content.domain.PartyTypeDataOnDemand;
import org.inbloom.content.domain.PartyTypeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PartyTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PartyTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PartyTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PartyTypeIntegrationTest: @Transactional;
    
    @Autowired
    PartyTypeDataOnDemand PartyTypeIntegrationTest.dod;
    
    @Test
    public void PartyTypeIntegrationTest.testCountPartyTypes() {
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", dod.getRandomPartyType());
        long count = PartyType.countPartyTypes();
        Assert.assertTrue("Counter for 'PartyType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PartyTypeIntegrationTest.testFindPartyType() {
        PartyType obj = dod.getRandomPartyType();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to provide an identifier", id);
        obj = PartyType.findPartyType(id);
        Assert.assertNotNull("Find method for 'PartyType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PartyType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PartyTypeIntegrationTest.testFindAllPartyTypes() {
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", dod.getRandomPartyType());
        long count = PartyType.countPartyTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PartyType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PartyType> result = PartyType.findAllPartyTypes();
        Assert.assertNotNull("Find all method for 'PartyType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PartyType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PartyTypeIntegrationTest.testFindPartyTypeEntries() {
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", dod.getRandomPartyType());
        long count = PartyType.countPartyTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PartyType> result = PartyType.findPartyTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PartyType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PartyType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PartyTypeIntegrationTest.testFlush() {
        PartyType obj = dod.getRandomPartyType();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to provide an identifier", id);
        obj = PartyType.findPartyType(id);
        Assert.assertNotNull("Find method for 'PartyType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPartyType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PartyType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartyTypeIntegrationTest.testMergeUpdate() {
        PartyType obj = dod.getRandomPartyType();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to provide an identifier", id);
        obj = PartyType.findPartyType(id);
        boolean modified =  dod.modifyPartyType(obj);
        Integer currentVersion = obj.getVersion();
        PartyType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PartyType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartyTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", dod.getRandomPartyType());
        PartyType obj = dod.getNewTransientPartyType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PartyType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PartyType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PartyType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PartyTypeIntegrationTest.testRemove() {
        PartyType obj = dod.getRandomPartyType();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PartyType' failed to provide an identifier", id);
        obj = PartyType.findPartyType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PartyType' with identifier '" + id + "'", PartyType.findPartyType(id));
    }
    
}
