// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import org.inbloom.content.domain.PartyTypeDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PartyTypeDataOnDemand_Roo_Configurable {
    
    declare @type: PartyTypeDataOnDemand: @Configurable;
    
}
