// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.PartyType;
import org.inbloom.content.domain.PartyTypeDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect PartyTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PartyTypeDataOnDemand: @Component;
    
    private Random PartyTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<PartyType> PartyTypeDataOnDemand.data;
    
    public PartyType PartyTypeDataOnDemand.getNewTransientPartyType(int index) {
        PartyType obj = new PartyType();
        setName(obj, index);
        return obj;
    }
    
    public void PartyTypeDataOnDemand.setName(PartyType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public PartyType PartyTypeDataOnDemand.getSpecificPartyType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PartyType obj = data.get(index);
        Long id = obj.getId();
        return PartyType.findPartyType(id);
    }
    
    public PartyType PartyTypeDataOnDemand.getRandomPartyType() {
        init();
        PartyType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PartyType.findPartyType(id);
    }
    
    public boolean PartyTypeDataOnDemand.modifyPartyType(PartyType obj) {
        return false;
    }
    
    public void PartyTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PartyType.findPartyTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PartyType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PartyType>();
        for (int i = 0; i < 10; i++) {
            PartyType obj = getNewTransientPartyType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
