// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.PathwayNode;
import org.inbloom.content.domain.PathwayNodeDataOnDemand;
import org.inbloom.content.domain.PathwayNodeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PathwayNodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PathwayNodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PathwayNodeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PathwayNodeIntegrationTest: @Transactional;
    
    @Autowired
    PathwayNodeDataOnDemand PathwayNodeIntegrationTest.dod;
    
    @Test
    public void PathwayNodeIntegrationTest.testCountPathwayNodes() {
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", dod.getRandomPathwayNode());
        long count = PathwayNode.countPathwayNodes();
        Assert.assertTrue("Counter for 'PathwayNode' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testFindPathwayNode() {
        PathwayNode obj = dod.getRandomPathwayNode();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to provide an identifier", id);
        obj = PathwayNode.findPathwayNode(id);
        Assert.assertNotNull("Find method for 'PathwayNode' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PathwayNode' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testFindAllPathwayNodes() {
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", dod.getRandomPathwayNode());
        long count = PathwayNode.countPathwayNodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PathwayNode', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PathwayNode> result = PathwayNode.findAllPathwayNodes();
        Assert.assertNotNull("Find all method for 'PathwayNode' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PathwayNode' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testFindPathwayNodeEntries() {
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", dod.getRandomPathwayNode());
        long count = PathwayNode.countPathwayNodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PathwayNode> result = PathwayNode.findPathwayNodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PathwayNode' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PathwayNode' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testFlush() {
        PathwayNode obj = dod.getRandomPathwayNode();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to provide an identifier", id);
        obj = PathwayNode.findPathwayNode(id);
        Assert.assertNotNull("Find method for 'PathwayNode' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPathwayNode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PathwayNode' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testMergeUpdate() {
        PathwayNode obj = dod.getRandomPathwayNode();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to provide an identifier", id);
        obj = PathwayNode.findPathwayNode(id);
        boolean modified =  dod.modifyPathwayNode(obj);
        Integer currentVersion = obj.getVersion();
        PathwayNode merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PathwayNode' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", dod.getRandomPathwayNode());
        PathwayNode obj = dod.getNewTransientPathwayNode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PathwayNode' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PathwayNode' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PathwayNodeIntegrationTest.testRemove() {
        PathwayNode obj = dod.getRandomPathwayNode();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PathwayNode' failed to provide an identifier", id);
        obj = PathwayNode.findPathwayNode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PathwayNode' with identifier '" + id + "'", PathwayNode.findPathwayNode(id));
    }
    
}
