// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Pathway;
import org.inbloom.content.domain.PathwayDataOnDemand;
import org.inbloom.content.domain.StandardDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PathwayDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PathwayDataOnDemand: @Component;
    
    private Random PathwayDataOnDemand.rnd = new SecureRandom();
    
    private List<Pathway> PathwayDataOnDemand.data;
    
    @Autowired
    StandardDataOnDemand PathwayDataOnDemand.standardDataOnDemand;
    
    public Pathway PathwayDataOnDemand.getNewTransientPathway(int index) {
        Pathway obj = new Pathway();
        setName(obj, index);
        return obj;
    }
    
    public void PathwayDataOnDemand.setName(Pathway obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Pathway PathwayDataOnDemand.getSpecificPathway(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Pathway obj = data.get(index);
        Long id = obj.getId();
        return Pathway.findPathway(id);
    }
    
    public Pathway PathwayDataOnDemand.getRandomPathway() {
        init();
        Pathway obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Pathway.findPathway(id);
    }
    
    public boolean PathwayDataOnDemand.modifyPathway(Pathway obj) {
        return false;
    }
    
    public void PathwayDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Pathway.findPathwayEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Pathway' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Pathway>();
        for (int i = 0; i < 10; i++) {
            Pathway obj = getNewTransientPathway(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
