// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.PathwayDataOnDemand;
import org.inbloom.content.domain.PathwayNode;
import org.inbloom.content.domain.PathwayNodeDataOnDemand;
import org.inbloom.content.domain.StandardDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PathwayNodeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PathwayNodeDataOnDemand: @Component;
    
    private Random PathwayNodeDataOnDemand.rnd = new SecureRandom();
    
    private List<PathwayNode> PathwayNodeDataOnDemand.data;
    
    @Autowired
    PathwayDataOnDemand PathwayNodeDataOnDemand.pathwayDataOnDemand;
    
    @Autowired
    StandardDataOnDemand PathwayNodeDataOnDemand.standardDataOnDemand;
    
    public PathwayNode PathwayNodeDataOnDemand.getNewTransientPathwayNode(int index) {
        PathwayNode obj = new PathwayNode();
        return obj;
    }
    
    public PathwayNode PathwayNodeDataOnDemand.getSpecificPathwayNode(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PathwayNode obj = data.get(index);
        Long id = obj.getId();
        return PathwayNode.findPathwayNode(id);
    }
    
    public PathwayNode PathwayNodeDataOnDemand.getRandomPathwayNode() {
        init();
        PathwayNode obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PathwayNode.findPathwayNode(id);
    }
    
    public boolean PathwayNodeDataOnDemand.modifyPathwayNode(PathwayNode obj) {
        return false;
    }
    
    public void PathwayNodeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PathwayNode.findPathwayNodeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PathwayNode' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PathwayNode>();
        for (int i = 0; i < 10; i++) {
            PathwayNode obj = getNewTransientPathwayNode(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
