// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Standard;
import org.inbloom.content.domain.StandardDataOnDemand;
import org.inbloom.content.domain.StandardIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StandardIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StandardIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StandardIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StandardIntegrationTest: @Transactional;
    
    @Autowired
    StandardDataOnDemand StandardIntegrationTest.dod;
    
    @Test
    public void StandardIntegrationTest.testCountStandards() {
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", dod.getRandomStandard());
        long count = Standard.countStandards();
        Assert.assertTrue("Counter for 'Standard' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StandardIntegrationTest.testFindStandard() {
        Standard obj = dod.getRandomStandard();
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standard' failed to provide an identifier", id);
        obj = Standard.findStandard(id);
        Assert.assertNotNull("Find method for 'Standard' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Standard' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StandardIntegrationTest.testFindAllStandards() {
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", dod.getRandomStandard());
        long count = Standard.countStandards();
        Assert.assertTrue("Too expensive to perform a find all test for 'Standard', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Standard> result = Standard.findAllStandards();
        Assert.assertNotNull("Find all method for 'Standard' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Standard' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StandardIntegrationTest.testFindStandardEntries() {
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", dod.getRandomStandard());
        long count = Standard.countStandards();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Standard> result = Standard.findStandardEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Standard' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Standard' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StandardIntegrationTest.testFlush() {
        Standard obj = dod.getRandomStandard();
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standard' failed to provide an identifier", id);
        obj = Standard.findStandard(id);
        Assert.assertNotNull("Find method for 'Standard' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStandard(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Standard' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StandardIntegrationTest.testMergeUpdate() {
        Standard obj = dod.getRandomStandard();
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standard' failed to provide an identifier", id);
        obj = Standard.findStandard(id);
        boolean modified =  dod.modifyStandard(obj);
        Integer currentVersion = obj.getVersion();
        Standard merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Standard' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StandardIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", dod.getRandomStandard());
        Standard obj = dod.getNewTransientStandard(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Standard' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Standard' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Standard' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StandardIntegrationTest.testRemove() {
        Standard obj = dod.getRandomStandard();
        Assert.assertNotNull("Data on demand for 'Standard' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Standard' failed to provide an identifier", id);
        obj = Standard.findStandard(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Standard' with identifier '" + id + "'", Standard.findStandard(id));
    }
    
}
