// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Use;
import org.inbloom.content.domain.UseDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect UseDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UseDataOnDemand: @Component;
    
    private Random UseDataOnDemand.rnd = new SecureRandom();
    
    private List<Use> UseDataOnDemand.data;
    
    public Use UseDataOnDemand.getNewTransientUse(int index) {
        Use obj = new Use();
        setName(obj, index);
        return obj;
    }
    
    public void UseDataOnDemand.setName(Use obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Use UseDataOnDemand.getSpecificUse(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Use obj = data.get(index);
        Long id = obj.getId();
        return Use.findUse(id);
    }
    
    public Use UseDataOnDemand.getRandomUse() {
        init();
        Use obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Use.findUse(id);
    }
    
    public boolean UseDataOnDemand.modifyUse(Use obj) {
        return false;
    }
    
    public void UseDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Use.findUseEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Use' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Use>();
        for (int i = 0; i < 10; i++) {
            Use obj = getNewTransientUse(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
