// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inbloom.content.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inbloom.content.domain.Use;
import org.inbloom.content.domain.UseDataOnDemand;
import org.inbloom.content.domain.UseIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UseIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UseIntegrationTest: @Transactional;
    
    @Autowired
    UseDataOnDemand UseIntegrationTest.dod;
    
    @Test
    public void UseIntegrationTest.testCountUses() {
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", dod.getRandomUse());
        long count = Use.countUses();
        Assert.assertTrue("Counter for 'Use' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UseIntegrationTest.testFindUse() {
        Use obj = dod.getRandomUse();
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Use' failed to provide an identifier", id);
        obj = Use.findUse(id);
        Assert.assertNotNull("Find method for 'Use' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Use' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UseIntegrationTest.testFindAllUses() {
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", dod.getRandomUse());
        long count = Use.countUses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Use', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Use> result = Use.findAllUses();
        Assert.assertNotNull("Find all method for 'Use' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Use' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UseIntegrationTest.testFindUseEntries() {
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", dod.getRandomUse());
        long count = Use.countUses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Use> result = Use.findUseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Use' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Use' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UseIntegrationTest.testFlush() {
        Use obj = dod.getRandomUse();
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Use' failed to provide an identifier", id);
        obj = Use.findUse(id);
        Assert.assertNotNull("Find method for 'Use' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUse(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Use' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UseIntegrationTest.testMergeUpdate() {
        Use obj = dod.getRandomUse();
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Use' failed to provide an identifier", id);
        obj = Use.findUse(id);
        boolean modified =  dod.modifyUse(obj);
        Integer currentVersion = obj.getVersion();
        Use merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Use' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UseIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", dod.getRandomUse());
        Use obj = dod.getNewTransientUse(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Use' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Use' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Use' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UseIntegrationTest.testRemove() {
        Use obj = dod.getRandomUse();
        Assert.assertNotNull("Data on demand for 'Use' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Use' failed to provide an identifier", id);
        obj = Use.findUse(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Use' with identifier '" + id + "'", Use.findUse(id));
    }
    
}
